#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xDBD2CE893E2D1C87 (cfeck@kde.org)
#
Name     : knotes
Version  : 18.08.0
Release  : 1
URL      : https://download.kde.org/stable/applications/18.08.0/src/knotes-18.08.0.tar.xz
Source0  : https://download.kde.org/stable/applications/18.08.0/src/knotes-18.08.0.tar.xz
Source99 : https://download.kde.org/stable/applications/18.08.0/src/knotes-18.08.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.2 GPL-2.0 LGPL-2.1
Requires: knotes-bin
Requires: knotes-lib
Requires: knotes-data
Requires: knotes-license
Requires: knotes-locales
BuildRequires : akonadi-contacts-dev
BuildRequires : akonadi-dev
BuildRequires : akonadi-mime-dev
BuildRequires : akonadi-notes-dev
BuildRequires : akonadi-search-dev
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : grantlee-dev
BuildRequires : kcalcore-dev
BuildRequires : kcalutils-dev
BuildRequires : kcontacts-dev
BuildRequires : kdnssd-dev
BuildRequires : kglobalaccel-dev
BuildRequires : kimap-dev
BuildRequires : kmime-dev
BuildRequires : knotifyconfig-dev
BuildRequires : kontactinterface-dev
BuildRequires : kpimtextedit-dev
BuildRequires : libX11-dev libICE-dev libSM-dev libXau-dev libXcomposite-dev libXcursor-dev libXdamage-dev libXdmcp-dev libXext-dev libXfixes-dev libXft-dev libXi-dev libXinerama-dev libXi-dev libXmu-dev libXpm-dev libXrandr-dev libXrender-dev libXres-dev libXScrnSaver-dev libXt-dev libXtst-dev libXv-dev libXxf86misc-dev libXxf86vm-dev
BuildRequires : libkdepim-dev
BuildRequires : pimcommon-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev
BuildRequires : qtx11extras-dev

%description
KNotes -- Notes for the K Desktop Environment
=============================================

%package bin
Summary: bin components for the knotes package.
Group: Binaries
Requires: knotes-data
Requires: knotes-license

%description bin
bin components for the knotes package.


%package data
Summary: data components for the knotes package.
Group: Data

%description data
data components for the knotes package.


%package doc
Summary: doc components for the knotes package.
Group: Documentation

%description doc
doc components for the knotes package.


%package lib
Summary: lib components for the knotes package.
Group: Libraries
Requires: knotes-data
Requires: knotes-license

%description lib
lib components for the knotes package.


%package license
Summary: license components for the knotes package.
Group: Default

%description license
license components for the knotes package.


%package locales
Summary: locales components for the knotes package.
Group: Default

%description locales
locales components for the knotes package.


%prep
%setup -q -n knotes-18.08.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535303395
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535303395
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/knotes
cp COPYING %{buildroot}/usr/share/doc/knotes/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/knotes/COPYING.DOC
cp COPYING.LIB %{buildroot}/usr/share/doc/knotes/COPYING.LIB
cp cmake/modules/COPYING-CMAKE-SCRIPTS %{buildroot}/usr/share/doc/knotes/cmake_modules_COPYING-CMAKE-SCRIPTS
pushd clr-build
%make_install
popd
%find_lang akonadi_notes_agent
%find_lang knotes
%find_lang libnoteshared

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/akonadi_notes_agent
/usr/bin/knotes

%files data
%defattr(-,root,root,-)
/usr/share/akonadi/agents/notesagent.desktop
/usr/share/applications/org.kde.knotes.desktop
/usr/share/config.kcfg/knotesglobalconfig.kcfg
/usr/share/config.kcfg/notesagentsettings.kcfg
/usr/share/dbus-1/interfaces/org.kde.KNotes.xml
/usr/share/dbus-1/interfaces/org.kde.kontact.KNotes.xml
/usr/share/icons/hicolor/128x128/apps/knotes.png
/usr/share/icons/hicolor/16x16/actions/knotes_alarm.png
/usr/share/icons/hicolor/16x16/actions/knotes_close.png
/usr/share/icons/hicolor/16x16/actions/knotes_date.png
/usr/share/icons/hicolor/16x16/actions/knotes_delete.png
/usr/share/icons/hicolor/16x16/apps/knotes.png
/usr/share/icons/hicolor/22x22/apps/knotes.png
/usr/share/icons/hicolor/32x32/apps/knotes.png
/usr/share/icons/hicolor/48x48/apps/knotes.png
/usr/share/icons/hicolor/64x64/apps/knotes.png
/usr/share/kconf_update/knotes-15.08-kickoff.sh
/usr/share/kconf_update/knotes.upd
/usr/share/knotes/print/themes/background-color/theme.desktop
/usr/share/knotes/print/themes/background-color/theme.html
/usr/share/knotes/print/themes/big-title/theme.desktop
/usr/share/knotes/print/themes/big-title/theme.html
/usr/share/knotes/print/themes/default/theme.desktop
/usr/share/knotes/print/themes/default/theme.html
/usr/share/knotifications5/akonadi_notes_agent.notifyrc
/usr/share/kontact/ksettingsdialog/knotes.setdlg
/usr/share/kservices5/kcmknotessummary.desktop
/usr/share/kservices5/knote_config_action.desktop
/usr/share/kservices5/knote_config_collection.desktop
/usr/share/kservices5/knote_config_display.desktop
/usr/share/kservices5/knote_config_editor.desktop
/usr/share/kservices5/knote_config_misc.desktop
/usr/share/kservices5/knote_config_network.desktop
/usr/share/kservices5/knote_config_print.desktop
/usr/share/kservices5/kontact/knotesplugin.desktop
/usr/share/kxmlgui5/knotes/knotes_part.rc
/usr/share/kxmlgui5/knotes/knotesappui.rc
/usr/share/kxmlgui5/knotes/knotesui.rc
/usr/share/metainfo/org.kde.knotes.appdata.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/ca/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/ca/knotes/index.cache.bz2
/usr/share/doc/HTML/ca/knotes/index.docbook
/usr/share/doc/HTML/de/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/de/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/de/knotes/index.cache.bz2
/usr/share/doc/HTML/de/knotes/index.docbook
/usr/share/doc/HTML/en/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/en/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/en/knotes/index.cache.bz2
/usr/share/doc/HTML/en/knotes/index.docbook
/usr/share/doc/HTML/en/knotes/select-notes-folder.png
/usr/share/doc/HTML/es/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/es/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/es/knotes/index.cache.bz2
/usr/share/doc/HTML/es/knotes/index.docbook
/usr/share/doc/HTML/et/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/et/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/et/knotes/index.cache.bz2
/usr/share/doc/HTML/et/knotes/index.docbook
/usr/share/doc/HTML/it/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/it/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/it/knotes/index.cache.bz2
/usr/share/doc/HTML/it/knotes/index.docbook
/usr/share/doc/HTML/nl/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/nl/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/nl/knotes/index.cache.bz2
/usr/share/doc/HTML/nl/knotes/index.docbook
/usr/share/doc/HTML/pt/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/pt/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/pt/knotes/index.cache.bz2
/usr/share/doc/HTML/pt/knotes/index.docbook
/usr/share/doc/HTML/pt_BR/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/pt_BR/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/pt_BR/knotes/index.cache.bz2
/usr/share/doc/HTML/pt_BR/knotes/index.docbook
/usr/share/doc/HTML/sv/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/sv/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/sv/knotes/index.cache.bz2
/usr/share/doc/HTML/sv/knotes/index.docbook
/usr/share/doc/HTML/uk/akonadi_notes_agent/index.cache.bz2
/usr/share/doc/HTML/uk/akonadi_notes_agent/index.docbook
/usr/share/doc/HTML/uk/knotes/index.cache.bz2
/usr/share/doc/HTML/uk/knotes/index.docbook

%files lib
%defattr(-,root,root,-)
/usr/lib64/libknotesprivate.so.5
/usr/lib64/libknotesprivate.so.5.9.0
/usr/lib64/libnotesharedprivate.so.5
/usr/lib64/libnotesharedprivate.so.5.9.0
/usr/lib64/qt5/plugins/kcm_knote.so
/usr/lib64/qt5/plugins/kcm_knotessummary.so
/usr/lib64/qt5/plugins/kontact_knotesplugin.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/knotes/COPYING
/usr/share/doc/knotes/COPYING.DOC
/usr/share/doc/knotes/COPYING.LIB
/usr/share/doc/knotes/cmake_modules_COPYING-CMAKE-SCRIPTS

%files locales -f akonadi_notes_agent.lang -f knotes.lang -f libnoteshared.lang
%defattr(-,root,root,-)

